### ISSUE TITLE
Firefox Addon missing

### ISSUE THREAD

**Issue by JeremyStarTM** [TimTrayler/darker-youtube#1]
I can't download the Firefox version since the Mozilla Firefox Addon Store tells me it never existed.

**Comment by TimTrayler** [comment]
Hello, this is an issue with the app violating the Mozilla Addons guidelines. I minified the hex2hsl library for quicker loading but Mozilla doesn't like that because it is not exactly like the source. I've already unminified and published it but Mozilla wrote me in an email that the review process is taking longer than expected. Until it is available again, you can still install the v2 crx file.

**Comment by JeremyStarTM** [comment]
Okay. I hope it get's resolved soon, and I don't want to use anything Chromium-based.

**Comment by TimTrayler** [comment]
The issue has been resolved as of today and the extension is back up in the store.

**Comment by JeremyStarTM** [comment]
Nice! Thank you.
